[package]
name = "example-block"
version = "0.1.0"
description = "A sample project with block wasm"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.79"
prost = { version = "0.6" }
prost-types = "0.6"

[build-dependencies]
prost-build = "0.6"